import "server-only";
import { createServiceSupabase } from "@/lib/supabase/service";
import { logAudit } from "@/lib/logging";
import type { ImportPlan } from "@/lib/import/parse";

export interface ImportDiff {
  newHolders: number;
  updatedHolders: number;
}

// Compare the plan against the DB to report new vs updated holders (preview).
export async function diffAgainstDb(plan: ImportPlan): Promise<ImportDiff> {
  const svc = createServiceSupabase();
  const emails = plan.holders.map((h) => h.email);
  if (emails.length === 0) return { newHolders: 0, updatedHolders: 0 };

  // .in() has practical URL limits; chunk the lookup.
  const existing = new Set<string>();
  for (let i = 0; i < emails.length; i += 200) {
    const chunk = emails.slice(i, i + 200);
    const { data } = await svc.from("holders").select("email").in("email", chunk);
    for (const r of data ?? []) existing.add(r.email);
  }
  let updated = 0;
  for (const e of emails) if (existing.has(e)) updated += 1;
  return { newHolders: emails.length - updated, updatedHolders: updated };
}

export interface ApplyResult {
  holdersUpserted: number;
  batchesInserted: number;
  departuresUpserted: number;
}

// Apply the plan. The file is the source of truth, so:
//  - holders are upserted by email (nda_accepted_at preserved — never reset).
//  - each imported holder's batches are FULL-REFRESHED (delete + reinsert),
//    because a grant can legitimately repeat (same name/strike) and vesting
//    figures change between exports.
//  - departure_tracking is upserted by holder_id.
export async function applyImport(plan: ImportPlan, actorEmail: string | null): Promise<ApplyResult> {
  const svc = createServiceSupabase();

  // 1. Upsert holders (omit nda_accepted_at to preserve acceptance).
  const holderRows = plan.holders.map((h) => ({
    email: h.email,
    first_name: h.first_name,
    last_name: h.last_name,
    holder_type: h.holder_type,
    employee_status: h.employee_status,
    is_founder: h.is_founder,
    matricule: h.matricule,
    matera_email: h.matera_email,
    contract_start_date: h.contract_start_date,
    ordinary_shares: h.ordinary_shares,
    needs_review: h.needs_review,
    has_login_email: h.hasLoginEmail,
    data_as_of: new Date().toISOString().slice(0, 10),
  }));

  const idByEmail = new Map<string, string>();
  for (let i = 0; i < holderRows.length; i += 200) {
    const chunk = holderRows.slice(i, i + 200);
    const { data, error } = await svc
      .from("holders")
      .upsert(chunk, { onConflict: "email" })
      .select("id, email");
    if (error) throw new Error(`Holder upsert failed: ${error.message}`);
    for (const r of data ?? []) idByEmail.set(r.email, r.id);
  }

  const holderIds = [...idByEmail.values()];

  // Note: magic-link access tokens are generated by the DB column DEFAULT on
  // insert (migration 0008), so new holders get one automatically and existing
  // tokens are preserved (the upsert above never touches access_token).

  // 2. Full-refresh batches: delete existing for these holders, then insert.
  for (let i = 0; i < holderIds.length; i += 200) {
    const chunk = holderIds.slice(i, i + 200);
    const { error } = await svc.from("batches").delete().in("holder_id", chunk);
    if (error) throw new Error(`Batch delete failed: ${error.message}`);
  }

  const batchRows: Array<Record<string, unknown>> = [];
  for (const h of plan.holders) {
    const holderId = idByEmail.get(h.email);
    if (!holderId) continue;
    for (const b of h.batches) {
      batchRows.push({
        holder_id: holderId,
        batch_name: b.batch_name ?? "",
        strike_price: b.strike_price,
        quantity: b.quantity,
        is_vested: b.is_vested,
        status: b.status,
        attribution_date: b.attribution_date,
        expiration_date: b.expiration_date,
        delegation: b.delegation,
        meta: b.meta,
      });
    }
  }
  for (let i = 0; i < batchRows.length; i += 500) {
    const chunk = batchRows.slice(i, i + 500);
    const { error } = await svc.from("batches").insert(chunk);
    if (error) throw new Error(`Batch insert failed: ${error.message}`);
  }

  // 3. Upsert departure_tracking (matched to a holder by email).
  const departureRows = plan.departures
    .map((d) => {
      const holderId = idByEmail.get(d.email);
      if (!holderId) return null;
      return {
        holder_id: holderId,
        uplaw_id: d.uplaw_id,
        gender: d.gender,
        postal_address: d.postal_address,
        departure_date: d.departure_date,
        departure_cause: d.departure_cause,
        theoretical_deadline: d.theoretical_deadline,
        exercise_deadline: d.exercise_deadline,
        bspce_granted: d.bspce_granted,
        bspce_vested_at_notif: d.bspce_vested_at_notif,
        price_label: d.price_label,
        no_extension: d.no_extension,
        admin_status: d.admin_status,
      };
    })
    .filter((r): r is NonNullable<typeof r> => r !== null);

  if (departureRows.length > 0) {
    const { error } = await svc
      .from("departure_tracking")
      .upsert(departureRows, { onConflict: "holder_id" });
    if (error) throw new Error(`Departure upsert failed: ${error.message}`);
  }

  // 4. Bump data freshness + audit.
  await svc
    .from("admin_settings")
    .upsert(
      { key: "data_last_refreshed_at", value: new Date().toISOString(), updated_by: actorEmail },
      { onConflict: "key" },
    );

  await logAudit({
    actorEmail,
    action: "data.imported",
    target: `${holderRows.length} holders, ${batchRows.length} batches`,
    after: plan.report,
  });

  return {
    holdersUpserted: holderRows.length,
    batchesInserted: batchRows.length,
    departuresUpserted: departureRows.length,
  };
}
